Updating to sync with SciDB 23.10
Paradigm4/extra-scidb-libs pull request #52
Opened 2023-11-06 17:59 UTC by jlevine-p4

2023-11-06 18:05 UTC, jlevine-p4 commented
Interesting. It failed a couple of tests because the workflow is still trying to use SciDB 22.6. The workflow files look like they point to version 23.2, I can update those to point to 23.10 and see if that helps.

2023-11-06 18:15 UTC, rvernica requested changes
Minor comments, please review

2023-11-06 18:15 UTC, rvernica commented on docker/rocky-8/res/install-scidb.sh
> +    "s/22.6/23.10/"                              \
This entire `sed` command should go away. Before this PR, I was downloading the 22.5 repo file (as there was not 22.6 repo) and replacing 22.5 with 22.6 in the repo file. 
Now you are downloading the 23.10 report and there is no need to replace anything.

2023-11-06 18:15 UTC, rvernica commented on install.sh
> +PKG_VER=0
We start with version 1

2023-11-06 18:15 UTC, rvernica commented on specs/extra-scidb-libs.spec
> +Version:        0
Version 1

2023-11-06 18:24 UTC, rvernica commented
Yes, update the workflow to use the 23.10 images. There are no 23.10 images yet. So, the workflow will still fail.
In parallel, I'll work on the 23.10 images and we should have this workflow succeed soon.

2023-11-10 18:30 UTC, rvernica approved these changes

2023-11-10 18:52 UTC, rvernica commented
I merged the master and resolved conflicts. I made some additional fixes. The locally built package tests successfully.

2023-11-10 18:52 UTC, merged